export const TUTORIAL_STEPS = Object.freeze([
  {
    id: "farmer_intro",
    speaker: "farmer",
    selectRole: "farmer",
    faceDown: true,
    text: "Welcome to Process V2. The loop is simple: take contracts, gather goods, farm food, make water, build homes and storage, defend the town, then expand again.",
  },
  {
    id: "top_bar",
    speaker: "farmer",
    highlight: "topHud",
    text: "The top bar is your stockpile. Food, water, wood, stone, seeds, money, permits and beds all decide how long the town keeps moving.",
  },
  {
    id: "tabs_intro",
    speaker: "farmer",
    openTab: "functions",
    highlight: "bottomTabs",
    speechPlacement: "top",
    text: "The bottom tabs hold your tools. Functions gives orders, Store buys buildings and units, Players manages workers, and the building tabs inspect town systems.",
  },
  {
    id: "farm_mode",
    speaker: "farmer",
    openTab: "functions",
    highlight: "farmButton",
    speechPlacement: "top",
    waitFor: { action: "function.mode", mode: "Farm" },
    allowedActions: [{ action: "function.mode", mode: "Farm" }],
    resumeSimulation: true,
    text: "Start with farming. Choose Farm in the Functions tab, or press F.",
  },
  {
    id: "farm_plots",
    speaker: "farmer",
    waitFor: { action: "farm.planted" },
    resumeSimulation: true,
    text: "Pick a crop area and confirm it. Your farmers will till and seed those tiles, spending stamina while they work.",
  },
  {
    id: "forager_intro",
    speaker: "forager",
    selectRole: "forager",
    text: "I handle the land outside town. Parcels add new space and resource nodes, so expansion feeds the rest of the loop.",
  },
  {
    id: "forest_contract_slot",
    speaker: "forager",
    forceDetailed: true,
    focusParcel: "E",
    hoverParcel: "E",
    highlight: "eastContractHud",
    speechPlacement: "contractBottom",
    waitFor: { action: "contractHud.slot", slotId: "E" },
    allowedActions: [{ action: "contractHud.slot", slotId: "E" }],
    resumeSimulation: true,
    text: "Parcels are bought from the contract HUD in detailed view. Open the EAST contract button now.",
  },
  {
    id: "forest_contract_type",
    speaker: "forager",
    highlight: "contractForestButton",
    speechPlacement: "contractBottom",
    waitFor: { action: "contractHud.type", slotId: "E", type: "FOREST" },
    allowedActions: [{ action: "contractHud.type", slotId: "E", type: "FOREST" }],
    resumeSimulation: true,
    text: "Choose Forest. That contract creates trees, and trees feed wood for storage, housing, and water.",
  },
  {
    id: "forest_contract_buy",
    speaker: "forager",
    highlight: "contractBuyButton",
    speechPlacement: "contractBottom",
    waitFor: { action: "parcel.commit", slotId: "E", type: "FOREST", source: "contractHud" },
    allowedActions: [{ action: "parcel.commit", slotId: "E", type: "FOREST", source: "contractHud" }],
    resumeSimulation: true,
    text: "Buy the Forest contract. Everything else is locked until this purchase is done.",
  },
  {
    id: "route_forager",
    speaker: "forager",
    selectRole: "forager",
    waitFor: { action: "forager.route", resourceType: "wood" },
    resumeSimulation: true,
    text: "With me selected, click a tree to route me to wood. I will gather it and haul it back when I can.",
  },
  {
    id: "builder_intro",
    speaker: "builder",
    selectRole: "builder",
    openTab: "build",
    setBuildMode: "buildings",
    speechPlacement: "top",
    text: "Builders turn supplies into structures. Storage raises item space, and houses give workers beds for sleep.",
  },
  {
    id: "build_house",
    speaker: "builder",
    openTab: "build",
    setBuildMode: "buildings",
    highlight: "buildHouseCard",
    speechPlacement: "top",
    waitFor: { action: "build.placed", key: "house" },
    allowedActions: [
      { action: "build.select", key: "house" },
      { action: "build.placed", key: "house" },
    ],
    resumeSimulation: true,
    text: "Build a House first. More beds let you recruit more help and keep tired workers from piling up homeless.",
  },
  {
    id: "build_storage",
    speaker: "builder",
    openTab: "build",
    setBuildMode: "buildings",
    highlight: "buildStorageCard",
    speechPlacement: "top",
    waitFor: { action: "build.placed", key: "storage" },
    allowedActions: [
      { action: "build.select", key: "storage" },
      { action: "build.placed", key: "storage" },
    ],
    resumeSimulation: true,
    text: "Now build Storage near your roads. Storage raises item space so wood, stone, food and water do not cap out as fast.",
  },
  {
    id: "fireman_intro",
    speaker: "fireman",
    selectRole: "fireman",
    openTab: "functions",
    highlight: "waterButton",
    speechPlacement: "top",
    text: "I make water. Water keeps farms and workers supplied, but production burns wood.",
  },
  {
    id: "water_on",
    speaker: "fireman",
    openTab: "functions",
    highlight: "waterButton",
    speechPlacement: "top",
    waitFor: { action: "function.water", enabled: true },
    allowedActions: [{ action: "function.water", enabled: true }],
    resumeSimulation: true,
    text: "Turn Water ON in Functions. Later, turn it off when you have enough so you do not drain your wood.",
  },
  {
    id: "buy_brawler",
    speaker: "brawler",
    openTab: "build",
    setBuildMode: "units",
    highlight: "buildUnitStoreArea",
    speechPlacement: "top",
    waitFor: { action: "build.recruit", key: "brawler" },
    allowedActions: [{ action: "build.recruit", key: "brawler" }],
    resumeSimulation: true,
    text: "Recruit one Brawler from Store > Units. Fighters protect the town when raiders show up at night.",
  },
  {
    id: "brawler_intro",
    speaker: "brawler",
    selectRole: "brawler",
    text: "I defend your town from nightly raiders. Keep fighters housed, fed, watered and rested before night starts.",
  },
  {
    id: "finish",
    speaker: "farmer",
    selectRole: "farmer",
    completeOnAdvance: true,
    text: "That is the core loop: farm, gather, build, make water, defend, and expand. The run can save normally after this.",
  },
]);
