// weapons.js
export const weapons = {
  hands : {
    name: "Hands",
    baseDmg: 10,
    critDmg: 15,
    critProb: 20,
    accuracy: 75,
    duration: 700,
    range: 46,
    projectile: false,
    attackSfxKey: "sfx_hand_punch",
    moveSlowMultiplier: 0.65,
    moveSlowDurationMs: 500,
  },

  boxingGloves: {
    name: "Boxing Gloves",
    baseDmg: 18,
    critDmg: 30,
    critProb: 25,
    accuracy: 80,
    duration: 700,
    range: 46,
    projectile: false,
    attackSfxKey: "sfx_boxing_punch",
    moveSlowMultiplier: 0.58,
    moveSlowDurationMs: 750,
  },

  sword: {
    name: "Sword",
    baseDmg: 45,
    critDmg: 85,
    critProb: 30,
    accuracy: 90,
    duration: 1000,
    range: 50,
    projectile: false,
    attackSfxKey: "sfx_sword_hit",
    moveSlowMultiplier: 0.62,
    moveSlowDurationMs: 850,
  },

  pistol: {
    name: "pistol",
    baseDmg: 100,
    critDmg: 175,
    critProb: 40,
    accuracy: 85,
    duration: 1000,
    range: 200,
    projectile: true,
    speed: 300,
    attackSfxKey: "sfx_gun_shot",
    moveSlowMultiplier: 0.72,
    moveSlowDurationMs: 650,
  },

  turret: {
    name: "turret",
    baseDmg: 42,
    critDmg: 68,
    critProb: 18,
    accuracy: 100,
    duration: 850,
    range: 310,
    projectile: true,
    speed: 340,
    attackSfxKey: "sfx_gun_shot",
  },

  catapult: {
    name: "catapult",
    baseDmg: 125,
    critDmg: 180,
    critProb: 24,
    accuracy: 100,
    duration: 2200,
    range: 400,
    projectile: true,
    speed: 205,
    attackSfxKey: null,
    projectileTextureKey: "rock_projectile",
    projectileFrame: 0,
    projectileAnimKey: "rock_projectile_spin",
    impactAtEndOnly: true,
    impactRadius: 18,
    projectileScaleStart: 0.82,
    projectileScaleEnd: 0.7,
    projectilePeakScaleMin: 1.28,
    projectilePeakScaleMax: 2.05,
  }
};
